pub const app = @import("src/app/app.zig");
pub const assets = struct {
    pub const image_catalog = @import("src/assets/image_catalog.zig");
    pub const runtime_image = @import("src/assets/runtime_image.zig");
};
pub const performance = @import("src/performance/frame_metrics.zig");
pub const platform = @import("src/platform/platform.zig");
pub const desktop_remote_image = @import("src/platform/desktop_remote_image.zig");
pub const render = @import("src/render/clay_renderer.zig");
pub const semantics = @import("src/ui/semantics.zig");
pub const text = @import("src/text/font.zig");
pub const ui = @import("src/ui/root.zig");

test {
    _ = @import("src/assets/image_catalog.zig");
    _ = @import("src/assets/runtime_image.zig");
    _ = app;
    _ = performance;
    _ = platform;
    _ = desktop_remote_image;
    _ = semantics;
    _ = text;
    _ = ui;
    _ = @import("src/render/image_decode.zig");
    _ = @import("src/render/image_cache.zig");
    _ = @import("src/render/image_registry.zig");
    _ = @import("src/ui/focus_manager.zig");
    _ = @import("src/ui/widgets/button.zig");
    _ = @import("src/ui/widgets/card.zig");
    _ = @import("src/ui/widgets/checkbox.zig");
    _ = @import("src/ui/widgets/divider.zig");
    _ = @import("src/ui/widgets/dialog.zig");
    _ = @import("src/ui/widgets/floating_window.zig");
    _ = @import("src/ui/widgets/icon_button.zig");
    _ = @import("src/ui/widgets/image_view.zig");
    _ = @import("src/ui/widgets/interaction.zig");
    _ = @import("src/ui/widgets/label.zig");
    _ = @import("src/ui/widgets/layer_layout.zig");
    _ = @import("src/ui/widgets/navigation_bar.zig");
    _ = @import("src/ui/widgets/progress_bar.zig");
    _ = @import("src/ui/widgets/scroll_view.zig");
    _ = @import("src/ui/widgets/scroll_bar.zig");
    _ = @import("src/ui/widgets/slider.zig");
    _ = @import("src/ui/widgets/switch.zig");
    _ = @import("src/ui/widgets/text_field.zig");
    _ = @import("src/ui/widgets/search_field.zig");
    _ = @import("src/ui/widgets/toast.zig");
    _ = @import("src/ui/widgets/tree_view.zig");
}
