pub const Model = struct {
    frame_count: u64 = 0,
    elapsed_seconds: f64 = 0,
    viewport_width: i32 = 1280,
    viewport_height: i32 = 720,
    dpi_scale: f32 = 1,
    pointer_x: f32 = 0,
    pointer_y: f32 = 0,
    pointer_down: bool = false,
    pointer_pressed: bool = false,
    pointer_released: bool = false,
    scroll_delta_x: f32 = 0,
    scroll_delta_y: f32 = 0,
    frame_delta_seconds: f32 = 0,
    primary_button_presses: u32 = 0,
    demo_checkbox_checked: bool = false,
    demo_switch_checked: bool = true,
    demo_progress: f32 = 0.35,
    demo_volume: f32 = 0.65,
    demo_dialog_open: bool = false,
    demo_dialog_confirmations: u32 = 0,
    back_requested: bool = false,
    focus_next_requested: bool = false,
    focus_previous_requested: bool = false,
    focused_control_activate_requested: bool = false,
    focused_control_left_requested: bool = false,
    focused_control_right_requested: bool = false,
    text_field_focused: bool = false,
    text_buffer: [256]u8 = @splat(0),
    text_length: usize = 0,
    text_submission_count: u32 = 0,
    demo_navigation_index: u8 = 0,
    suspended: bool = false,

    pub fn text(self: *const Model) []const u8 {
        return self.text_buffer[0..self.text_length];
    }
};
